### ISSUE TITLE
LINT WARNING: Type instantiation is excessively deep and possibly infinite.ts(2589)

### ISSUE THREAD

**Issue by david8z** [viandwi24/nuxt3-awesome-starter#10]
On fresh install I see this warning 🤔  any idea about it?
![Screenshot 2022-05-07 at 16 30 52](https://user-images.githubusercontent.com/31882023/167258704-b8f3b725-455c-46df-b0a9-8162b2fd1f18.png)

**Comment by viandwi24** [comment]
this is warning? but program can launch normal?

**Comment by david8z** [comment]
Yeah program can launch normal.

**Comment by david8z** [comment]
This issues has been addressed on https://github.com/nuxt/framework/discussions/4754

**Comment by viandwi24** [comment]
thanks, I've updated the nuxt version to solve this problem.
In this commit https://github.com/viandwi24/nuxt3-awesome-starter/commit/6bd32daba2c3ec452e577d8475e3455f1f24e1a7
