### ISSUE TITLE
[vite] Internal server error: Undefined variable.  

### ISSUE THREAD

**Issue by retrogradeMT** [viandwi24/nuxt3-awesome-starter#13]
following the quickstart leads to an error on unspecified variables sass variables.    I am not sure what I am missing
```
     Error: Undefined variable.
      ╷
   4 │       $color1 20%,
      │       ^^^^^^^
     pages/index.vue 4:7  root stylesheet
```

and also

 ```
 Error: Undefined variable.
    ╷
  3 │   font-family: $fontFamily !important;
    │                ^^^^^^^^^^^
    ╵
    assets/sass/app.scss 3:16  root stylesheet
    ```

**Comment by viandwi24** [comment]
can you reproduce it? (into codesanbox for example)

or the first step, try to do a clean node_modules then try running "yarn install" again.

or re-clone this repository again.

**Comment by Priebojp** [comment]
If you update `nuxt-windicss` to version bigger than 2.3.1, you can reproduce this error.
With the default project setting everything is ok. (at least for me).

**Comment by Robert-Hung** [comment]
Internal server error: [sass] Undefined variable.
   ╷
67 │           background: $primary-color;
   │                       ^^^^^^^^^^^^^^
   ╵
  resources\sass\_about.scss 67:23  root stylesheet 
  
help me
