### ISSUE TITLE
problem with hotReload.. 

### ISSUE THREAD

**Issue by whipsterCZ** [viandwi24/nuxt3-awesome-starter#16]
sometimes i have to restart   "yarn dev" and refresh browser.. 
maybe its just nuxt3 , maybe Tailwind

**Comment by Zac-Zajdel** [comment]
Try clearing your browsers cache and see if that fixes things for yah. I have had similar issues with Nuxt 3 in particular on my computer.

**Comment by viandwi24** [comment]
have you used this template in the latest commit version?

I've made some improvements such as disabling attributes on windicss.

the hot reload problem on windicss should be resolved.

**Comment by whipsterCZ** [comment]
Hello. i can gladly confirm that commit   #ce100e4eb116bd3519eae5e750532094f005035c fixed the issue

thank you..
