### ISSUE TITLE
Vue Router and intlify Warning

### ISSUE THREAD

**Issue by SuperService** [viandwi24/nuxt3-awesome-starter#17]
this is realy awesome starter for nuxt3
but I am getting Vue Router and intlify Warning
etc:
1. [Vue Router warn]: No match found for location with path "/__webpack_hmr"
2. [intlify] Not found 'banners.welcome' key in 'ko' locale messages.
[intlify] Fall back to translate 'banners.welcome' key with 'en' locale.
Could you have solution?

**Comment by viandwi24** [comment]
did you add a new language with code "ko" ?

**Comment by SuperService** [comment]
thanks for your response
I don't added code "ko"
I can't understand over warning in your project
only my browser language code is 'ko'

**Comment by viandwi24** [comment]
is your browser language "ko-korean"?

**Comment by SuperService** [comment]
yes all right

**Comment by viandwi24** [comment]
ah, it means that this warning appears because this template tries to find out the system language, then looks for it in the locales datashet. because the default language provided is en so they are trying to return en.

**Comment by viandwi24** [comment]
I tried to check the locales that are registered first, if there is not it will still return to "en", maybe this will get rid of the warning earlier.
https://github.com/viandwi24/nuxt3-awesome-starter/commit/c1091cacffb4140903589d146d5c45f18d5d007f

**Comment by SuperService** [comment]
yes
so what is yur solution to remove warning?

**Comment by viandwi24** [comment]
try doing a git pull to receive my latest commit update.  
this commit should be https://github.com/viandwi24/nuxt3-awesome-starter/commit/c1091cacffb4140903589d146d5c45f18d5d007f help

**Comment by viandwi24** [comment]
your welcome, and i tried to add korean language too in this latest commit https://github.com/viandwi24/nuxt3-awesome-starter/commit/84737af47af10378aee72602e8e49949173305ac

I only use a direct language translator, if there are errors maybe you can contribute hahaha.

thanks!

**Comment by SuperService** [comment]
thanks @viandwi 👏👏👏
I have 3 beginer question(not issues)
I am cloning your awesome starter with nuxt3 init app
1. can't use variable in app.scss
    error: $fontFamily: undefined variable
    I think that this is sass setting problem😂
2. I already used locale files with .json but you used .yml file
    what do you prefer .json vs .yml?
3. Your Components Architecture
    // state:styles
    const styles = reactive<{[key: string]: string}>(...)
    👀 why do you use 'reactive' instead of 'ref'?
    // state
    const selectedXXX = computed(() => {...});
    👀why do you use computed?

**Comment by SuperService** [comment]
Awesome Answer ✨
thanks for your detail response
My Understand
1. solution is windi.css version ( < 2.3.1)
2. good
3. reactive(sometimes not working with dynamic data)
    etc (Vue Apex Chart Library...)
   computed(detect change porps and then force rerendering with style)

My understand is right?
