### ISSUE TITLE
The deployment problem

### ISSUE THREAD

**Issue by Rosethorn99** [viandwi24/nuxt3-awesome-starter#18]
This happens after running yarn build and then yarn start 
![image](https://user-images.githubusercontent.com/40927708/175328216-d834bbba-c42d-46d7-a498-04a4f7590c2d.png)

**Comment by viandwi24** [comment]
can you attach more details about this error, and did you get this error on fresh installation?

I can only surmise you're doing something that still doesn't seem supported on nuxt 3.
