### ISSUE TITLE
JWT Auth

### ISSUE THREAD

**Issue by ironytr** [viandwi24/nuxt3-awesome-starter#2]
Hello would you mind add JWT auth for this project? Thank you.

**Comment by viandwi24** [comment]
nice feature, in the future I plan to add useful but simple like this jwt auth. But before that, I will try to add http request library first.

maybe you can add a reference as well as to what jwt auth or library can be added.

thank you and have a nice day!

**Comment by ironytr** [comment]
Hello, im not js expert which librarys are right for it i dont have a clue. Since there is no nuxt3 auth repos, for a starter project should have auth capabilities. Well this looking like a personal problem yet if you could make it would be no1 repo for start nuxt3 project. I want to learn nuxt by newest version (I know there is alot ppl like me). So im struggling with axios and jwt auth not working. (im using inertiajs vue2 had done dashboard). https://echo.labstack.com/cookbook/jwt/ this is the project i will use for backend. Simple backend. Nuxt2 auth module works good tho.

**Comment by viandwi24** [comment]
thanks for the suggestion, i have put it in the to do list, after adding the axios http request, i will add the auth module afterwards.
