### ISSUE TITLE
Text input not reactive

### ISSUE THREAD

**Issue by airDjura** [viandwi24/nuxt3-awesome-starter#21]
I fixed issue for myself by replacing @input="onInput" and :value="modelValue" with v-model="modelValue"
and olso onInput method is not needed anymore
![image](https://user-images.githubusercontent.com/22389169/178007324-19bb243e-9b78-4d7a-b744-ecbcc92c51ff.png)

**Comment by viandwi24** [comment]
Ah, thanks for reminding me, yesterday I re-created this component text input again from scratch, and forgot to add v-model instead of :value.

I do not pay attention to whether the text input still works or not. thanks.

Or, if u have time for pull request this fix.
