### ISSUE TITLE
Where can i remove this startup animation

### ISSUE THREAD

**Issue by 5SMNOONMS5** [viandwi24/nuxt3-awesome-starter#25]
![Screen Shot 2022-08-08 at 7 21 37 PM](https://user-images.githubusercontent.com/8379901/183407051-b5297171-ee4b-4061-9af5-a55f2601d3de.png)

Because I will like to speed up my DX, so i will like to remove this animation but I can't find where is the code, even I empty entire APP.vue still the same

**Comment by viandwi24** [comment]
sorry, this is a building vite animation done by nuxt.

so not from this template project. This animation is purely from nuxt 3. This animation shows that the page is not ready because it is still in the building stage.

**Comment by 5SMNOONMS5** [comment]
> sorry, this is a building vite animation done by nuxt.
> 
> so not from this template project. This animation is purely from nuxt 3. This animation shows that the page is not ready because it is still in the building stage.

thx , but is this possible to close it ??

**Comment by viandwi24** [comment]
if i may know what do you want to remove this for?

This animation only appears when we are developing Nuxt, when in production this animation will not appear

**Comment by 5SMNOONMS5** [comment]
> if i may know what do you want to remove this for?
> 
> This animation only appears when we are developing Nuxt, when in production this animation will not appear

Sorry for late reply. Because I have several project in hands. Just don't wanna to wait about 10 seconds. Not so big deal. 
And thx for the replay
