### ISSUE TITLE
.husky/pre-commit: line 4: yarn: command not found husky - pre-commit hook exited with code 127 (error) husky - command not found in PATH=/Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core:/usr/bin:/bin:/usr/sbin:/sbin

### ISSUE THREAD

**Issue by ChurikiTenna** [viandwi24/nuxt3-awesome-starter#31]
I have cloned the repository, and made some changes.
When I tried to commit, this error appear:

.husky/pre-commit: line 4: yarn: command not found
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=/Applications/GitHub Desktop.app/Contents/Resources/app/git/libexec/git-core:/usr/bin:/bin:/usr/sbin:/sbin

I have done all sorts of stuff, but error consists.. Please kindly help me..
https://dev.to/studiospindle/using-husky-s-pre-commit-hook-with-a-gui-21ch
https://stackoverflow.com/questions/67063993/sh-husky-command-not-found

**Comment by viandwi24** [comment]
hali sir, as I allow on readme.md

this project uses "yarn" as the main package manager. so make sure you install "thread" in your device.
