### ISSUE TITLE
Why slut?

### ISSUE THREAD

**Issue by mohsin** [viandwi24/nuxt3-awesome-starter#43]
Please [explain the naming being slut.vue](https://github.com/viandwi24/nuxt3-awesome-starter/blob/main/pages/post/%5Bslut%5D.vue).

I mean, Github starting using `main` instead of `master` coz of the whole slave-master thing despite the context being to computers. This a whole another level.

<img width="1158" alt="Screenshot 2022-12-09 at 21 49 18" src="https://user-images.githubusercontent.com/1699753/206746038-d21a8134-8b13-4b4e-9997-41ae59a0904f.png">

**Comment by viandwi24** [comment]
it's been fixed here

https://github.com/viandwi24/nuxt3-awesome-starter/pull/44

**Comment by mohsin** [comment]
Cool cool. 👍🏽

**Comment by zhurbiyDigitalLite** [comment]
It was better
