### ISSUE TITLE
Cannot find package 'c12' imported from

### ISSUE THREAD

**Issue by Mohammad-Khayat** [viandwi24/nuxt3-awesome-starter#5]
after installing node modules i got this error
ERROR  Cannot start nuxt:  Cannot find package 'c12' imported from C:\Users\Moham\Desktop\Git Repos\my-nuxt3-app\node_modules\nuxt-windicss\node_modules\@nuxt\kit\dist\index.mjs

**Comment by viandwi24** [comment]
could you try to pull/re-clone, then run everything from scratch?

tried removing /node_modules then running the "yarn install" command again.

if the error still persists, can you create a minimal reproduction.
