### ISSUE TITLE
V2 Major Update

### ISSUE THREAD

**Issue by viandwi24** [viandwi24/nuxt3-awesome-starter#56]
i plan to change the structure for the better, and work on integrating with Nuxt Layers.
this is one very nice feature, which is that others can easily extend this template with their own templates.

## To Dos
- [x] #60
  - [x] create modules `~/modules/awesome.ts`
- [x] Adding Pinia
  - [x] auto import "defineStore" as "definePiniaStore"
  - [x] auto import folder "stores"
- [x] Eslint & Prettier
- [x] 🌙 Theme Switcher (light, dark, system)
- [x] Easy App Config
  - [x] App Meta (title, authors)
  - [x] Layout (navbar menus)

**Comment by laportem** [comment]
When is the ETA for v2

**Comment by viandwi24** [comment]
![image](https://raw.githubusercontent.com/viandwi24/nuxt3-awesome-starter/v2/assets/images/preview.png)

V2 Branch : https://github.com/viandwi24/nuxt3-awesome-starter/tree/v2
Live Demo : https://nuxt3-awesome-starter-git-v2-viandwi24.vercel.app/
