### ISSUE TITLE
Document not found when deploying the project

### ISSUE THREAD

**Issue by jamols09** [viandwi24/nuxt3-awesome-starter#62]
I get a document not found after uploading the project to AWS S3.

Ran the commands
`pnpm build`
`pnpm generate`

![image](https://user-images.githubusercontent.com/20100579/235134222-465ce178-48b9-46ab-96e9-6a84aaa61c56.png)

**Comment by LtDylan** [comment]
You can't use ```pnpm build``` with ```pnpm generate```.

```pnpm generate``` is used to deploy a static site. Nuxt is building and generating the application in plain HTML files. This command must be used alone : the result given is already ready to use as a static hosting.

```pnpm build``` is used to build the application with Vite or Webpack for production. It's not a static site as the previous command. After this command, you have to use ```pnpm start``` to get your application working in production.

You can learn more about these commands in the doc : 
```generate``` https://nuxt.com/docs/api/commands/generate
```build``` https://nuxt.com/docs/api/commands/build
