### ISSUE TITLE
Sunsetting Windi

### ISSUE THREAD

**Issue by mazipan** [viandwi24/nuxt3-awesome-starter#63]
https://windicss.org/posts/sunsetting.html

**Comment by viandwi24** [comment]
yes in next version i have removed windi using tailwind native. and trying to consider whether to switch to unocss

**Comment by FranciscoKloganB** [comment]
I whole heartadly recommend that you stick with tailwindcss. I love open source, but Tailwind is maintained by a team that is fully dedicated to it, not by a group of open source maitainers with a bunch of products under their belt. Also Tailwind is moving quite fast performance and feature wise, and the plugin libraries are just amazing. Unocss is brilliant but is more niche. At the end of the day it depends on how many people you'd want using your template.

**Comment by viandwi24** [comment]
> I whole heartadly recommend that you stick with tailwindcss. I love open source, but Tailwind is maintained by a team that is fully dedicated to it, not by a group of open source maitainers with a bunch of products under their belt. Also Tailwind is moving quite fast performance and feature wise, and the plugin libraries are just amazing. Unocss is brilliant but is more niche. At the end of the day it depends on how many people you'd want using your template.


thanks for your advice, I just released the latest update of this template and switched to using tailwindcss
