### ISSUE TITLE
pnpm run dev cannot run project

### ISSUE THREAD

**Issue by kleptoplasty** [viandwi24/nuxt3-awesome-starter#67]
When I execute 'pnpm run dev' command，I can open this project, but the console keeps returning 503 errors
![image](https://github.com/viandwi24/nuxt3-awesome-starter/assets/71555875/065b52b6-cc27-45c8-8d18-4e4870aa26c3)

**Comment by Bayn-Web** [comment]
i meet this problem too. how can i fix it?

**Comment by JasonLiuLiuLiuLiu** [comment]
I also have this issue

**Comment by JasonLiuLiuLiuLiu** [comment]
After deleting the .demo folder, it can work.

**Comment by duoluodexiaoxiaoyuan** [comment]
> After deleting the .demo folder, it can work.

Do you know what the reason is?
