### ISSUE TITLE
How to deploy  this project to my own server？

### ISSUE THREAD

**Issue by kleptoplasty** [viandwi24/nuxt3-awesome-starter#69]
I have written a blog website using this template and want to deploy it to my own server. How do I implement this？

**Comment by kleptoplasty** [comment]
I have written a blog website using this template and want to deploy it to my own server. How do I implement this？

**Comment by viandwi24** [comment]
nuxt 3 has many ways you can use it to deploy, but in the main case there are 2 ways you can do it, namely:

- static
you can do this with `pnpm generate` then nuxt will generate a dist/ folder which you can upload directly to the server.
i used this for upload demo to free static hosting like vercel, netlify, dll.

- universal
you can do it with `pnpm build`, then serve to the server you can use the `pnpm preview` shortcut or directly run `node app/.output/server/index.mjs`
